describe('testing click Slide Shoping in Jakarta notebook', () => {
    it('First checking visit web jakarta notebook use', () => {
        cy.visit('https://www.jakartanotebook.com/')
        cy.url().should('include','jakartanotebook.com')
        cy.get('.SelectBranchButton___StyledDiv3-sc-1oov5eu-5 > .Button__StyledButton-sc-1l0qx1m-2').click()
    })
    it('Try Click slide in navbar recomended item and click', () => {
        cy.get('.bx-next').click()
        cy.wait(5000)
        cy.get('.bx-next').click()
        cy.wait(5000)
        cy.get('.bx-next').click()
        cy.wait(5000)
        cy.get('.bx-next').click()
        cy.wait(5000)
        cy.get('.bx-next').click()
        cy.wait(5000)
        cy.get('.bx-next').click()
        cy.wait(5000)
        cy.get('.bx-next').click()
        cy.wait(5000)
        cy.get('.bx-next').click()
        cy.wait(5000)
        cy.get('.bx-next').click()
        cy.wait(5000)
        cy.get('.home__banner__slider > :nth-child(2) > img').click()
        cy.wait(5000)
    })
    
})